% Read the data
clc;clear;close all;
%data = dlmread('/Users/mczhang/Documents/GitHub/FM4/02-data/Kaiwen_websit.txt');

data = dlmread('/Users/mczhang/Documents/GitHub/FM4/02-data/Axial.MLDD.v202112.txt');

% Convert year, month, day, hour, minute, second to datenum
datenum_vals = datenum(data(:,1), data(:,2), data(:,3), ...
                      data(:,4), data(:,5), data(:,6));

% Create a structure with cell arrays
eventData = struct(...
    'datenum', num2cell(datenum_vals), ...
    'lat', num2cell(data(:,7)), ...
    'lon', num2cell(data(:,8)), ...
    'depth', num2cell(data(:,9)), ...
    'errorx', num2cell(data(:,10)), ...
    'errory', num2cell(data(:,11)), ...
    'errorz', num2cell(data(:,12)), ...
    'magnitude', num2cell(data(:,13)), ...
    'eventID', num2cell(data(:,14)));

% Alternative: Create a more compact structure with array fields
eventDataArray = struct(...
    'datenum', datenum_vals, ...
    'lat', data(:,7), ...
    'lon', data(:,8), ...
    'depth', data(:,9), ...
    'errorx', data(:,10), ...
    'errory', data(:,11), ...
    'errorz', data(:,12), ...
    'magnitude', data(:,13), ...
    'eventID', data(:,14));

% Save to a .mat file
save('Kaiwen_eventData_website.mat', 'eventData');  % Cell array version
% OR
%save('eventDataArray.mat', 'eventDataArray');  % Numeric array version