c dang0 : minimum grid spacing (degrees)
c ncoor : number of test mechanisms
c ncoor2 : max number of stored mechanisms (<ncoor*nmc0)

c choose one, based on your computer's memory and speed
c      parameter (dang0=10.0,ncoor=4032,ncoor2=40000) 
c      parameter (dang0=7.0,ncoor=10426,ncoor2=100000) 
      parameter (dang0=5.0,ncoor=31032,ncoor2=300000) 
c      parameter (dang0=3.0,ncoor=141180,ncoor2=1500000) 
c      parameter (dang0=2.0,ncoor=472410,ncoor2=5000000) 
